class LoginPageLocators:
    EMAIL_INPUT = "input[name='email']"
    PASSWORD_INPUT = "input[name='password']"
    LOGIN_BUTTON = "button[type='submit']"
    REGISTER_LINK = "a[href='/register']"
    ERROR_MESSAGE = ".bg-red-50"
    REMEMBER_CHECKBOX = "input#remember-me"

class RegisterPageLocators:
    USERNAME_INPUT = "input[name='username']"
    EMAIL_INPUT = "input[name='email']"
    PASSWORD_INPUT = "input[name='password']"
    CONFIRM_PASSWORD_INPUT = "input[name='confirmPassword']"
    FULL_NAME_INPUT = "input[name='full_name']"
    PHONE_INPUT = "input[name='phone']"
    BIRTH_DATE_INPUT = "input[name='birth_date']"
    ADDRESS_INPUT = "input[name='address']"
    ROLE_TENANT_BUTTON = "//button[contains(text(), 'Penyewa')]"
    ROLE_OWNER_BUTTON = "//button[contains(text(), 'Pemilik')]"
    TERMS_CHECKBOX = "input#terms"
    REGISTER_BUTTON = "button[type='submit']"
    LOGIN_LINK = "a[href='/login']"

class NavbarLocators:
    LOGO = "img[alt='Vida View Logo']"
    BERANDA_LINK = "a[href='/']"
    UNIT_LINK = "a[href='/apartments']"
    PROFILE_BUTTON = ".flex.items-center.space-x-2"
    NOTIFICATION_BUTTON = "a[href='/notifications']"
    NOTIFICATION_BADGE = ".bg-red-600.rounded-full"
    LOGOUT_BUTTON = "//button[contains(text(), 'Keluar')]"
    DASHBOARD_LINK = "//a[contains(text(), 'Dashboard')]"

class ApartmentsPageLocators:
    SEARCH_INPUT = "input[placeholder*='Cari']"
    FILTER_STATUS = "select"
    APARTMENT_CARD = ".bg-white.rounded-lg.shadow-md"
    APARTMENT_TITLE = "h3.font-semibold"
    APARTMENT_PRICE = ".text-purple-600.font-bold"
    VIEW_DETAIL_BUTTON = "//button[contains(text(), 'Lihat Detail')]"
    FAVORITE_BUTTON = "button[title='Add to favorites']"
    PAGINATION_NEXT = "//button[contains(text(), 'Next')]"
    NO_RESULTS = "//p[contains(text(), 'Tidak Ada Apartemen')]"

class ApartmentDetailLocators:
    UNIT_NUMBER = "h1.text-3xl.font-bold"
    UNIT_TYPE = ".text-lg.text-gray-600"
    PRICE = ".text-3xl.font-bold.text-purple-600"
    BOOKING_BUTTON = "//button[contains(text(), 'Booking Sekarang')]"
    CONTACT_OWNER_BUTTON = "//button[contains(text(), 'Hubungi Pemilik')]"
    FAVORITE_BUTTON = "//button[contains(., 'Favorit')]"
    BACK_BUTTON = "//button[contains(text(), 'Kembali')]"
    IMAGE_GALLERY = ".swiper-slide img"
    BEDROOMS = "//p[contains(text(), 'Kamar Tidur')]/following-sibling::p"
    BATHROOMS = "//p[contains(text(), 'Kamar Mandi')]/following-sibling::p"
    FACILITIES_LIST = ".grid.gap-3"

class BookingPageLocators:
    START_DATE_INPUT = "input[name='start_date']"
    END_DATE_INPUT = "input[name='end_date']"
    NOTES_TEXTAREA = "textarea[name='notes']"
    PROMO_CODE_INPUT = "input[placeholder*='promosi']"
    APPLY_PROMO_BUTTON = "//button[contains(text(), 'Terapkan')]"
    REMOVE_PROMO_BUTTON = "//button[contains(text(), 'Hapus')]"
    SUMMARY_TOTAL = ".text-3xl.font-bold"
    SUBMIT_BUTTON = "button[type='submit']"
    BACK_BUTTON = "//button[contains(text(), 'Kembali')]"
    APPLIED_PROMO_CODE = ".bg-green-50 .font-semibold"

class PaymentPageLocators:
    BANK_TRANSFER_OPTION = "//div[contains(text(), 'Bank Transfer')]"
    CREDIT_CARD_OPTION = "//div[contains(text(), 'Kartu Kredit')]"
    EWALLET_OPTION = "//div[contains(text(), 'E-Wallet')]"
    TRANSACTION_ID_INPUT = "input[placeholder*='transaksi']"
    RECEIPT_UPLOAD = "input#receipt-upload"
    NOTES_INPUT = "textarea[placeholder*='Catatan']"
    CONFIRM_BUTTON = "//button[contains(text(), 'Konfirmasi Pembayaran')]"
    NEXT_BUTTON = "//button[contains(text(), 'Lanjutkan')]"
    PREVIOUS_BUTTON = "//button[contains(text(), 'Kembali')]"

class DocumentsPageLocators:
    UPLOAD_BUTTON = "//button[contains(., 'Upload Dokumen')]"
    DOCUMENT_TYPE_SELECT = "select"
    FILE_INPUT = "input#document-upload"
    UPLOAD_MODAL_BUTTON = "//button[contains(text(), 'Upload Dokumen')]"
    VIEW_BUTTON = "//button[contains(., 'Lihat')]"
    VERIFICATION_STATUS = ".bg-green-100, .bg-yellow-100"
    KTP_CARD = "//h3[contains(text(), 'Kartu Identitas')]"
    SELFIE_CARD = "//h3[contains(text(), 'Foto Selfie')]"

class DashboardLocators:
    STATS_CARD = ".bg-white.rounded-lg.shadow-md"
    WELCOME_MESSAGE = ".bg-gradient-to-r"
    BOOKING_CARD = ".space-y-4 > div"
    QUICK_ACTION = "//a[contains(@class, 'hover:shadow-lg')]"

class AdminDashboardLocators:
    USERS_LINK = "a[href='/admin/users']"
    BOOKINGS_LINK = "a[href='/admin/bookings']"
    PAYMENTS_LINK = "a[href='/admin/payments']"
    PROMOTIONS_LINK = "a[href='/admin/promotions']"
    REPORTS_LINK = "a[href='/admin/reports']"
    STATS_CARD = ".grid.gap-6 > div"

class UserManagementLocators:
    SEARCH_INPUT = "input[name='search']"
    ROLE_FILTER = "select[name='role']"
    STATUS_FILTER = "select[name='status']"
    USER_ROW = "tbody tr"
    EDIT_BUTTON = "button[title='Edit']"
    DELETE_BUTTON = "button[title='Hapus']"
    VERIFY_BUTTON = "button[title='Verifikasi Dokumen']"
    VIEW_DOCS_BUTTON = "button[title='Lihat Dokumen']"
    SAVE_BUTTON = "//button[contains(text(), 'Simpan')]"
    CONFIRM_DELETE_BUTTON = "//button[contains(text(), 'Hapus')]"

class PromotionLocators:
    ADD_PROMO_BUTTON = "//button[contains(., 'Tambah Promosi')]"
    PROMO_CODE_INPUT = "input[placeholder*='Kode']"
    PROMO_TITLE_INPUT = "input[placeholder*='Judul']"
    PROMO_TYPE_SELECT = "select[value]"
    PROMO_VALUE_INPUT = "input[type='number']"
    START_DATE_INPUT = "input[name='start_date']"
    END_DATE_INPUT = "input[name='end_date']"
    ACTIVE_CHECKBOX = "input[type='checkbox']"
    SUBMIT_BUTTON = "//button[contains(text(), 'Tambah')]"
    EDIT_BUTTON = "//button[contains(., 'Edit')]"
    DELETE_BUTTON = "//button[contains(., 'Hapus')]"
    PROMO_CARD = ".bg-white.rounded-xl.shadow-md"

class OwnerUnitsLocators:
    ADD_UNIT_BUTTON = "//button[contains(., 'Tambah Unit')]"
    UNIT_CARD = ".relative > div"
    VIEW_BUTTON = "button[title='Lihat Detail']"
    EDIT_BUTTON = "button[title='Edit']"
    DELETE_BUTTON = "button[title='Hapus Unit']"
    ARCHIVE_BUTTON = "button[title='Arsipkan']"
    FILTER_ALL = "//button[contains(text(), 'Semua')]"
    FILTER_AVAILABLE = "//button[contains(text(), 'Tersedia')]"
    FILTER_OCCUPIED = "//button[contains(text(), 'Terisi')]"

class AddUnitModalLocators:
    UNIT_NUMBER_INPUT = "input[placeholder*='nomor']"
    UNIT_TYPE_SELECT = "select"
    BEDROOMS_INPUT = "input[name='bedrooms']"
    BATHROOMS_INPUT = "input[name='bathrooms']"
    SIZE_INPUT = "input[placeholder*='luas']"
    FLOOR_INPUT = "input[placeholder*='Lantai']"
    PRICE_INPUT = "input[placeholder*='harga']"
    DEPOSIT_INPUT = "input[placeholder*='deposit']"
    DESCRIPTION_TEXTAREA = "textarea"
    FURNISHED_CHECKBOX = "input[type='checkbox']"
    PHOTO_UPLOAD = "input[type='file']"
    SUBMIT_BUTTON = "//button[contains(text(), 'Tambah')]"
    CANCEL_BUTTON = "//button[contains(text(), 'Batal')]"